'use client';

import Link from 'next/link';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CircleAlert, Code2, FileText, GitCompareArrows, ShieldCheck } from 'lucide-react';
import { useWorkspace } from '@/components/workspace-provider';
import { Avatar, CopyButton } from '@/components/ui';
import { resolveSample, type SampleState } from '@/lib/sample-data';

export function Coordination() {
  const { state } = useWorkspace();
  return <><div className="page-heading"><div><div className="eyebrow">BEFORE YOU BUILD</div><h1>Coordination</h1><p>Find the overlap. Agree on the boundary. Keep building.</p></div></div><div className="section-heading"><h2>{state.resolution ? 'Recorded decisions' : 'Needs a look'}</h2><span className="count">1</span></div><Link href="/coordination/sample-check" className="check-list-card"><span className="context-icon"><GitCompareArrows size={24} aria-hidden="true" /></span><div><span className={`small-label ${state.resolution ? 'success-text' : 'warning-text'}`}>{state.resolution ? 'SAMPLE RESOLUTION SAVED' : 'LIKELY DUPLICATE · SAMPLE FINDING'}</span><h2>Personal shortlist ↔ Saved-college API</h2><p>Two requests that share an outcome. A frontend / backend split may make sense.</p><span className="muted small">Sam + Sri · 1 shared prompt cited · Code coverage unavailable</span></div><ArrowRight size={20} aria-hidden="true" /></Link><div className="inline-note"><ShieldCheck size={18} aria-hidden="true" /><p>Checks are advisory by default. A missing provider or missing evidence must stay “unknown.” This example does not call Jev.</p></div></>;
}

export function CheckDetail() {
  const { state, update } = useWorkspace();
  const [action, setAction] = useState<NonNullable<SampleState['resolution']>['action']>('coordinate');
  const [objective, setObjective] = useState('Build the shortlist interface using Sam’s planned saved-college API. Own the UI and loading, empty, and error states. Leave API implementation and persistence with Sam.');
  const [error, setError] = useState('');
  const original = 'Build a personal shortlist so people can save colleges and manage their choices. Include the backend needed to store each person’s list.';
  const continuation = state.resolution ? `SAMPLE CONTEXT — not a live resolution reference\n\nMy revised objective: ${state.resolution.objective}\n\nRelated work: Sam is working on the saved-college API (feature/saved-colleges).\nPlanned interface: GET /api/saved; POST /api/saved { collegeId }. This contract has not been implemented or accepted by both builders.\nScope: change only my task; do not take over Sam’s work.\nLimitations: synthetic fixture, no source snapshot, no provider check, no adapter delivery.` : '';
  function save(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!objective.trim()) { setError('Describe your next step before saving.'); return; }
    const success = update(current => resolveSample(current, action, objective), 'Sample decision saved in this browser.');
    setError(success ? '' : 'Your decision was not saved. Try again.');
  }
  return <><Link className="back-link" href="/coordination"><ArrowLeft size={15} aria-hidden="true" />Coordination</Link><div className="page-heading"><div><div className="eyebrow">CHECK / SAMPLE-01</div><h1>A shared outcome. Two possible paths.</h1><p>Sam’s backend may already cover part of your shortlist request.</p></div><span className="status status-needs_coordination"><CircleAlert size={14} aria-hidden="true" />{state.resolution ? 'Decision recorded' : 'Review suggested'}</span></div>
    <div className="comparison-grid"><section className="comparison-card"><span className="small-label">YOUR REQUEST</span><div className="comparison-owner"><Avatar name="Sri" small /><strong>Sri</strong><code>feature/shortlist</code></div><h2>Personal shortlist</h2><p>{original}</p><Link className="text-link" href="/sessions/sample-sri#sri-request">Open original prompt <ArrowRight size={14} aria-hidden="true" /></Link></section><section className="comparison-card"><span className="small-label">RELATED TEAM WORK</span><div className="comparison-owner"><Avatar name="Sam" small /><strong>Sam</strong><code>feature/saved-colleges</code></div><h2>Saved-college API</h2><p>Create the saved-college endpoints, persistence, and per-user access checks.</p><Link className="text-link" href="/sessions/sample-sam#sam-request">Open supporting prompt <ArrowRight size={14} aria-hidden="true" /></Link></section></div>
    <div className="detail-grid"><div><section className="evidence-section"><div className="section-heading"><h2>Why these requests overlap</h2><span className="muted small">Scripted example</span></div><div className="evidence-box"><div className="evidence-label"><FileText size={16} aria-hidden="true" /><strong>Shared intent</strong><span>Sample evidence · Oct 3, 2026, 10:32 AM</span></div><blockquote>“Each person should be able to save, list, and remove their own colleges. I’ll own the backend and access checks.”</blockquote><p>Both requests include storing and managing a person’s saved colleges. The interface can be a complementary task.</p><Link className="text-link" href="/sessions/sample-sam#sam-request">Sam’s original prompt <ArrowRight size={14} aria-hidden="true" /></Link></div><div className="coverage-message"><Code2 size={18} aria-hidden="true" /><div><strong>Code evidence: unavailable</strong><p>No source snapshot was checked. A planned interface is not an implemented API.</p></div></div></section>
    <section className="resolution-section"><div className="section-heading"><h2>{state.resolution ? 'Your saved next step' : 'Choose your next step'}</h2></div>{state.resolution ? <div className="resolution-saved"><span className="small-label success-text"><Check size={15} aria-hidden="true" />SAVED IN THIS BROWSER</span><h3>{state.resolution.action === 'coordinate' ? 'A proposed split of the work' : 'Your scope decision'}</h3><p>{state.resolution.objective}</p><div className="inline-note"><CircleAlert size={16} aria-hidden="true" /><p>Only Sri’s sample task changed. Sam has not accepted a new boundary. No agent has received this context.</p></div><h3>Context preview</h3><pre className="context-preview">{continuation}</pre><CopyButton value={continuation} label="Copy sample continuation" /><button className="button button-ghost" onClick={() => update(current => ({ ...current, resolution: null }), 'Sample decision reopened. Your task scope is unchanged.')}>Reopen decision</button></div> : <form className="resolution-form" onSubmit={save}><fieldset><legend>How would you like to proceed?</legend><div className="action-options">{[
      { id: 'coordinate', title: 'Coordinate', text: 'Propose a complementary scope.' },
      { id: 'revise', title: 'Revise my task', text: 'Narrow or change my objective.' },
      { id: 'reuse', title: 'Use existing context', text: 'Carry the planned interface forward.' },
      { id: 'proceed', title: 'Proceed separately', text: 'Record why a separate task is needed.' },
    ].map(option => <label className={`action-option ${action === option.id ? 'chosen' : ''}`} key={option.id}><input type="radio" name="resolution" value={option.id} checked={action === option.id} onChange={() => setAction(option.id as typeof action)} /><span><strong>{option.title}</strong><span>{option.text}</span></span></label>)}</div></fieldset><label htmlFor="objective">My next objective</label><textarea id="objective" value={objective} onChange={event => setObjective(event.target.value)} maxLength={2000} rows={4} required aria-describedby={error ? 'objective-error' : 'objective-help'} aria-invalid={!!error} /><p id="objective-help" className="muted small">This changes your sample task only. A teammate must accept changes to their responsibility.</p>{error && <p id="objective-error" role="alert" className="error-text">{error}</p>}<button type="submit" className="button button-primary">Save sample decision<ArrowRight size={15} aria-hidden="true" /></button></form>}</section></div>
    <aside className="detail-aside"><h2>Check details</h2><dl><dt>Source</dt><dd>Curated sample fixture</dd><dt>Task relationship</dt><dd>Likely duplicate outcome</dd><dt>Code coverage</dt><dd>Unknown · no snapshot</dd><dt>Provider</dt><dd>Not connected</dd><dt>Policy</dt><dd>Advisory</dd></dl><div className="principle-note"><ShieldCheck size={18} aria-hidden="true" /><strong>Evidence before certainty.</strong><p>Real checks must cite authorized, current sources. An unavailable provider can never produce a clear result.</p></div></aside></div></>;
}
